"""empty message

Revision ID: f2f9b7755c62
Revises:
Create Date: 2023-03-26 21:28:16.866216

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'f2f9b7755c62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('profile_pic_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('zodiac', sa.String(length=40), nullable=True),
    sa.Column('height', sa.String(length=20), nullable=True),
    sa.Column('relationship_status', sa.String(), nullable=True),
    sa.Column('birthday', sa.String(length=20), nullable=True),
    sa.Column('motto', sa.String(length=50), nullable=True),
    sa.Column('card_img_url', sa.String(), nullable=True),
    sa.Column('profile_background_img_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('text_color', sa.String(), nullable=True),
    sa.Column('theme_color', sa.String(), nullable=True),
    sa.Column('trim_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")

    op.create_table('booleans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name_b', sa.Boolean(), nullable=True),
    sa.Column('last_name_b', sa.Boolean(), nullable=True),
    sa.Column('bio_b', sa.Boolean(), nullable=True),
    sa.Column('birthday_b', sa.Boolean(), nullable=True),
    sa.Column('zodiac_b', sa.Boolean(), nullable=True),
    sa.Column('height_b', sa.Boolean(), nullable=True),
    sa.Column('motto_b', sa.Boolean(), nullable=True),
    sa.Column('card_b', sa.Boolean(), nullable=True),
    sa.Column('relationship_b', sa.Boolean(), nullable=True),
    sa.Column('background_b', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE booleans SET SCHEMA {SCHEMA};")

    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_rank', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE friends SET SCHEMA {SCHEMA};")

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('mood', sa.String(length=40), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE posts SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('friends')
    op.drop_table('booleans')
    op.drop_table('users')
    # ### end Alembic commands ###
