"""empty message

Revision ID: 4b5412f3296f
Revises: 
Create Date: 2023-03-25 11:01:45.704972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5412f3296f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('profile_pic_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('zodiac', sa.String(length=40), nullable=True),
    sa.Column('height', sa.String(length=20), nullable=True),
    sa.Column('relationship_status', sa.String(), nullable=True),
    sa.Column('birthday', sa.String(length=20), nullable=True),
    sa.Column('motto', sa.String(length=255), nullable=True),
    sa.Column('card_img_url', sa.String(), nullable=True),
    sa.Column('profile_background_img_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('booleans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name_b', sa.Boolean(), nullable=True),
    sa.Column('last_name_b', sa.Boolean(), nullable=True),
    sa.Column('bio_b', sa.Boolean(), nullable=True),
    sa.Column('birthday_b', sa.Boolean(), nullable=True),
    sa.Column('zodiac_b', sa.Boolean(), nullable=True),
    sa.Column('height_b', sa.Boolean(), nullable=True),
    sa.Column('motto_b', sa.Boolean(), nullable=True),
    sa.Column('card_b', sa.Boolean(), nullable=True),
    sa.Column('relationship_b', sa.Boolean(), nullable=True),
    sa.Column('background_b', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_rank', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('mood', sa.String(length=40), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('friends')
    op.drop_table('booleans')
    op.drop_table('users')
    # ### end Alembic commands ###